/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_chPPnHOzM",
    "aws_user_pools_web_client_id": "753e4kpfehvqs6jc95qm3lf5pe",
    "oauth": {}
};


export default awsmobile;